### ISSUE TITLE
Subdirectory installation + nginx as reverse proxy doesn't work well

### ISSUE THREAD

**Issue by SathyaBhat** [andris9/mailtrain#14]
Hi,

I was trying to install & run Mailtrain off a subdirectory but it seems to run into a problem, particularly when trying to login.

The issue is that Mailtrain is installed on http://example.com/campaigns, clicking on login changes the URL to  http://example.com/users/login instead of http://example.com/campaigns/users/login

this is the nginx config file I used

```
server {
    listen 80;
    listen [::]:80;

    server_name example.com;
    access_log /var/log/nginx/mailtrain.log;
    error /var/log/nginx/mailtrain_err.log;
    location /campaigns {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;
    }
}

```

I've also tried a variant of 

    rewrite ^/campaigns/?(.*) /campaigns/$1 break;

Both cases the redirect goes to http://example.com/users/login and results in a 404

**Comment by andris9** [comment]
Subdirectories are currently not supported. You could get it partly working by using `rewrite ^/campaigns(/.*)$ $1 break;` rule but as all static files (css, javascript etc.) are loaded from the root path, then the website would not work properly. Is there a reason you want Mailtrain to work from a folder instead of using a subdomain?

**Comment by SathyaBhat** [comment]
Hi @andris9 

I'm currently using Mailtrain for [Barcamp Bangalore](https://barcampbangalore.org) and we've had different webapps on subdirectories, so was continuing that approach.

For now though I have Mailtrain installed on subdirectory and it works fine. Thanks for this :)

**Comment by SudoHenk** [comment]
Real subdir support should be nice. I'd like to have every mail manament tool under one subdomain so that I can protect it from the web with a single HTTP BASIC AUTH password.

Creating a seperate subdomain for all these tools is painstakingly annoying with different password requests for every domain and getting SSL to work etc.

**Comment by osixia** [comment]
Is this possible to re open this ? It's clearly a minimum requirement. Third party apps must fits in existing architectures.

**Comment by UrGuardian4ngel** [comment]
Sorry for waking up a sleeping thread. But are there plans to support a configurable subdirectory, out of the box?

I recently ran into the same requirements, and have been fiddling around with the sources a bit myself.
For now, it seems to work fine behind an _nginx_ reverse proxy, under a customizable base directory via config... Well, at least for the functionalities I'm currently using.

---

Modified sources can be found in [my personal fork](/UrGuardian4ngel/mailtrain/commits/configurable-base-dir).
_– Warning for the faint of heart: I'm **not** a front-end developer!_ 😜
