### ISSUE TITLE
Feature Request: Order of questions on the signup page can't be changed

### ISSUE THREAD

**Issue by bensulli** [andris9/mailtrain#157]
I'd like to be able to re-order the questions asked on the signup page. I create 6 custom fields, but they seem to show up in a random order when you go to subscribe, and sometimes the questions won't make sense in a different order than they were intended.

I'll look for a way to force this (IDs?) in the meantime, but an official way to reorder custom fields on the subscribe page would be awesome!

Example: https://mailer.blueprintreality.com/subscription/SJEKKEU9g
I want comments/notes to be the last field.

**Comment by andris9** [comment]
Yeah, I see the issue here. Unfortunately it does not get reasonable fix any time soon as it would require messing around with the UI which is not priority right now. I did change the code a bit to ensure the fields are sorted by ID in ascending order. So if you want to make sure the comment field is last, then upgrade Mailtrain and manually edit your database – open the custom_fields table, find the comment field and then change the ID value to larger number than other fields have.

**Comment by bensulli** [comment]
I'm more than happy with that solution, thanks!
