### ISSUE TITLE
Segment Rule Feature: Allow date range to support relative timeframe filter

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#55]
We've typically done rules where we look back the last 60 days or 8 months. We'd love to see a date filter that allows this kind of filtering. It'd be nice to say either ## days or ## months and provide a number. This number would then be used to segment the list by a fixed date range on campaign send. 

Example, a segment has a filter of 60 days by signup date. The campaign starts on 5/1/2016. The actual filter would be the exclusively previous 60 days. 3/1/2016 - 4/30/2016.

Thanks for the consideration.

**Comment by andris9** [comment]
I pushed relative date range support to master branch, you can see the docs for it in the [wiki](https://github.com/andris9/mailtrain/wiki/Relative-date-ranges-in-segments). I haven't tagged it yet because it is kind of beta but you can already try it out if you use it if use the code from the master branch.

**Comment by radleta** [comment]
I just pulled the latest and the relative is very nice. Thanks.
