### ISSUE TITLE
Redis Scaling Question

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#59]
Do I need to have Redis connected to launch more instances of mailtrain to improve the send rate? Or, is it possible to just launch the mailtrain application on multiple servers and ignore Redis when not using them as part of the web farm?

**Comment by andris9** [comment]
At this point you do not need to share Redis between instances as it is only there to persist session data for authenticated users. Running multiple instances of Mailtrain against the same MySQL backend should be safe. 

There might be collisions in managing the queue but Mailtrain guarantees that no user gets the same email twice. If both instances try to send to the same recipient then the instance that manages to store this entry to the log first can actually perform the sending (Mailtrain follows at-most-once delivery rule). The other instance fails to insert data to the log because of duplicate primary key error, so it drops the message. Nevertheless it has already spent some time to get into that state and this means that queue processing might not be very much faster with multiple instances if you get a lot of collisions. This is something that yet needs to be addressed.

Redis might become more important in the future as I want to start using it to manage sending queues. MySQL is really good for storing data but not so good for rapidly adding and removing stuff - this is where Redis shines.
