### ISSUE TITLE
Import and .gitignore

### ISSUE THREAD

**Issue by shamank** [andris9/mailtrain#63]
Hi. I've just imported a new subscriber list and I found out that it's saving it in the root directory of the project under a hashed name "31f15acd12cf331620d1341518ac98d6". Another thing is that I created the config/production.toml file but it's not being ignored by the repository. I think everything/all toml files inside "config" should be ignored in gitignore. Maybe a good distribution standard for the template file "default.toml" should be "default.toml.sample" like everybody does. Thanks.

**Comment by andris9** [comment]
I updated gitignore to ignore development and production config files. The file structure comes from the [config](https://www.npmjs.com/package/config) module and I want to keep the default.toml to guarantee that default values exist when running Mailtrain. From time to time I add new default values and these must be present when you update your code and restart the service.

Import files are uploaded to CWD if the service is started using `npm start`. For whatever reason npm overrides system temp directory (where the import files should actually end up) with CWD. I changed the upstart script to use `node index.js` instead of `npm start`. Import files are not deleted automatically in case your import fails, so you can restart the import without re-uploading the file. If the file resides in tmp then it should be cleared with the next reboot anyway.

**Comment by shamank** [comment]
I've added the rule to force the tmp folder to /tmp.
I know everyone will notice it but I'll report it anyway. The commented code in default.toml is wrong:
`#tmpdir=/tmp`
Should be:
`#tmpdir="/tmp"`
