### ISSUE TITLE
sending a website

### ISSUE THREAD

**Issue by preexo** [andris9/mailtrain#8]
Is there a plan to add a feature which allows sending existing websites? Since I think mailtrain could be a really nice alternative to phplist, but they have this implemented in this way:  
![2016-04-06 18_59_10-phplist __ phplist __ send a campaign](https://cloud.githubusercontent.com/assets/1478410/14314490/0a4169ec-fc2a-11e5-9522-cbd4359d705d.png)

Just curious if this is on the roadmap.

**Comment by andris9** [comment]
Good idea, I'll add this to my list of to-do's

**Comment by lightonflux** [comment]
Don't forget a preview when implementing this feature.

**Comment by bago** [comment]
Please note that sending a website is a NON-SENSE and it simply WON'T work.
The HTML supported by email clients is almost another language than the HTML you use in an email: maybe you can send it to apple mail or to iphone, but your email won't be readable at all by most other email clients. And probably your email will be filtered by antispam filters that will see weird html they are not used to see.

So, webpage to email is only useful if you KNOW how to make an email template and you use your own website server-side language to compose your email using your server-side content, but it is useless (and very bad) if you think you can send a webpage created for the web.

**Comment by preexo** [comment]
@bago I totally disagree. We have been doing it this way through phplist since many years and it totally makes sense to us. Our mails are usually first available as a website and then we send them out a little delayed. This workflow has proven to end up with better emails for us.
Yes, you are right, you can't just use Dreamweaver to click together a web page and expect it to look good on any email client. Also I wouldn't try slicing a psd. Don't expect your wordpress/joomla code to look fine on any email client... HTML Emails simply only allow a subset of HTML to work fine across the client list.
But we know what is possible in HTML emails and our emails always look fantastic on all different email clients, you just need to know what you should avoid doing. We code our mails by hand, but for the ones that don't know it as well, I know there is many tools out there which will help you generate Email-friendly HTML code which looks great on all devices and clients.

There is a strong use case for this feature request and especially since established mailing applications have implemented it, we would miss the feature and couldn't do the switch.

It does work and it is definitely not non-sense to do so. 

I honestly don't understand why you would be so much against this feature, you won't have to use it in the end mate.

**Comment by bago** [comment]
Well, I send emails for living since 2003 and I developed responsive html email template, too, including developing an open source editor to make html email. I also run a small competitor of Mailchimp since 2008, and YES, we implemented the "retrieve the content from an URL" feature, so I have thousands of customers sending emails and I think I have the opportunity to see what issues are more frequent than others.

It is simply NOT TRUE that you "have to know what to avoid": email clients are a PITA. People wouldn't pay 79$/month and more for Litmus or similar services, otherwise.
I just spent a week fighting with "the next Outlok 2016 issue": http://mosaico.io/email-client-tricks/outlook-2016-weird-1px-horizontal-lines/

You probably think everything is working fine, but to be sure this is true you have to test dozen of smartphones, with their specific email clients, or using webmails via smartphone, and test all of the Outlook PC versions (because Outlook 2016 have quirks that you don't see in Outlook 2013 and so on).

BTW, what I wrote is that sending a webpage is NOT a good idea.
Sending an HTML email published via http can work, if you are a good template author: but this is not "sending a webpage".

The code to implement this feature is probably less than 50 lines of code (including UI), but the cost of this feature include that the general UI/UX will get more complex to satisfy a "minor feature" (somewhere you have to put a button to do this) and the cost include answering github issues for people saying that their homepage is not sent correclty by mailtrain beucase it doesn't work as expected (or it is not received at all because of spam filters), while the issue is that their HTML was not OK for email clients.

BTW, this is simply my suggestion to "sending a website" suggestion, not "retrieving the html email template from an URL" suggestion. Words matter. What users expect is not always what technology can really do (and viceversa).

I think mailtrain author can take hints and suggestions from anyone and then decide what to do. I explained in detail my concerns.

**Comment by preexo** [comment]
Yeah, I think your concerns make a lot of sense, I hope the mailtrain contributors keep them in mind and maybe the feature should not be as obviously available as in phplist. The feature could be hidden and only for users that are really sure they need this and know what risks it brings with it... Like myself ;)

By the way, I read your mosaico blog post about the outlook 2016 issues a couple of weeks ago. 
Thanks for sharing your insights there, it was very valuable! Mosaico is a great project and if it actually makes it way into mailtrain as well, it would be marvelous!

The name of the feature is simply what phplist calls it and made sense to me to keep calling it that way to make sure people understand what I mean. But... Let's call it "retrieve the content from an URL" from now on, thanks for pointing out the technical difference!

**Comment by MaheshCasiraghi** [comment]
@bago, @andris9, the feature @preexo is proposing makes a lot of sense to me too. Producing a template with a Foundation Emails assets compiling workflow, publishing the minified version to S3, and sending it through Mailtrain makes so much more sense to me that updating (and maintaining) a complicated and heavy new email editor. Let me know if this is in roadmap, and we'll give Mailtrain a Spin. Keep up with the good work.

**Comment by andris9** [comment]
I'm not sure how other services exactly handle this. Would it make more sense to fetch the URL contents immediatelly when setting up the campaign or fetch it separately for every message or even make a POST call with merge tags values for every message?

**Comment by MaheshCasiraghi** [comment]
@andris9, what would make a lot of sense to me, and probably others interested in using the tool both for campaign and for transactional middleman between a backend and SES, is the possibility to post to an endpoint - representing a specific template - a http POST request with a payload, containing merge tags. Then the system triggering a POST with the template with the merged tags to SES. Is this functionality already present in mailtrain? I have been playing around with it when it was on HN, but as of now I keep on having a nasty MYSQL connection timeout (also experienced by my colleagues trying to install the package, both 1.1 and 1.2 from scratch) which prevents further exploration. Is it possible that a npm dependency of mysql is broken? ps> It looks like we all have a correctly running instance of MYSQL with a correctly configured db and config (it actually worked 10 days ago). I should probably open a separate issue for this, but for brevity here below the logs: 

ERR! Import Error: Handshake inactivity timeout
ERR! Import     at Handshake.<anonymous> (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:160:17)
ERR! Import     at emitNone (events.js:67:13)
ERR! Import     at Handshake.emit (events.js:166:7)
ERR! Import     at Handshake._onTimeout (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
ERR! Import     at Timer.listOnTimeout (timers.js:92:15)
ERR! Import     --------------------
ERR! Import     at Protocol._enqueue (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:141:48)
ERR! Import     at Protocol.handshake (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:52:41)
ERR! Import     at PoolConnection.connect (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/Connection.js:123:18)
ERR! Import     at Pool.getConnection (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/Pool.js:45:23)
ERR! Import     at findUnprocessed (/Users/maheshcasiraghi/mailtrain/services/importer.js:14:8)
ERR! Import     at findUnprocessed (/Users/maheshcasiraghi/mailtrain/services/importer.js:224:9)
ERR! Import     at db.getConnection.fields.list.fieldList.forEach.inputStream.on.parser.on.Object.keys.forEach.tools.validateEmail.getNext (/Users/maheshcasiraghi/mailtrain/services/importer.js:262:5)
ERR! Import     at db.getConnection.fields.list.fieldList.forEach.inputStream.on.parser.on.Object.keys.forEach.tools.validateEmail.module.exports.callback (/Users/maheshcasiraghi/mailtrain/services/importer.js:266:5)
ERR! Import     at Immediate._onImmediate (/Users/maheshcasiraghi/mailtrain/index.js:75:13)
ERR! Import     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Mail Error: connect ETIMEDOUT
ERR! Mail     at PoolConnection.Connection._handleConnectTimeout (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/Connection.js:412:13)
ERR! Mail     at Socket.g (events.js:260:16)
ERR! Mail     at emitNone (events.js:67:13)
ERR! Mail     at Socket.emit (events.js:166:7)
ERR! Mail     at Socket._onTimeout (net.js:318:8)
ERR! Mail     at _runOnTimeout (timers.js:524:11)
ERR! Mail     at _makeTimerTimeout (timers.js:515:3)
ERR! Mail     at Timer.unrefTimeout (timers.js:584:5)
ERR! Mail     --------------------
ERR! Mail     at Protocol._enqueue (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:141:48)
ERR! Mail     at Protocol.handshake (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:52:41)
ERR! Mail     at PoolConnection.connect (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/Connection.js:123:18)
ERR! Mail     at Pool.getConnection (/Users/maheshcasiraghi/mailtrain/node_modules/mysql/lib/Pool.js:45:23)
ERR! Mail     at Object.listValues [as list] (/Users/maheshcasiraghi/mailtrain/lib/models/settings.js:20:8)
ERR! Mail     at createMailer (/Users/maheshcasiraghi/mailtrain/lib/mailer.js:85:14)
ERR! Mail     at Object.module.exports.getMailer.callback [as getMailer] (/Users/maheshcasiraghi/mailtrain/lib/mailer.js:21:16)
ERR! Mail     at db.getConnection.connection.query.campaigns.get.lists.get.settings.list.fields.list.mailer.getMailer.findUnsent (/Users/maheshcasiraghi/mailtrain/services/sender.js:226:12)

**Comment by andris9** [comment]
@MaheshCasiraghi this feature is not in Mailtrain yet but I intend to add it and are looking for the best approach for it. Using POST with merge values would be the most flexible solution so I'm considering this approach.

To fix the MySQL connection issue then you might try adding the following to the MySQL configuration, even though I'm not sure if it helps or not since I don't have this issue myself.

```
[mysql]
…
acquireTimeout=30000
```

**Comment by andris9** [comment]
I have this feature now experimentally available in the v1.3 branch ([docs here](https://github.com/andris9/mailtrain/wiki/Using-external-URL-as-HTML-message)). If an URL is provided instead of message template then every time the message needs to be rendered a POST request with all merge tags is done against that URL and the response is used as message contents.
