### ISSUE TITLE
Apache config for running Mailtrain?

### ISSUE THREAD

**Issue by flocu** [andris9/mailtrain#90]
Sorry for this Linux newbie question...

When I run install.sh on a fresh VPS with Ubuntu 16.04 64 Bit it terminates with a success message. But all I get shown at port 80 is the default Apache Ubuntu site.

What should the Apache config look like to run Mailtrain? Do I have to grant file system permissions?

Thank you!

**Comment by andris9** [comment]
If you do need Apache then it would be easier to just uninstall it (and then restart Mailtrain)

    sudo apt-get remove apache2*

Otherwise you would need to configure Mailtrain to use other port than 3000 and then add a new virtual host to /etc/apache/sites-enabled that uses mod_proxy to send all request to the Mailtrain installation

**Comment by flocu** [comment]
Thanks, that helped. Mailtrain running now :) 

I was under the impression Apache would be necessary to run mailtrain and also it was preinstalled by my VPS provider...
